[package]
name = "nanji"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.9"
colored = "2.1"
