[package]
name = "nanji"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.10.4"
colored = "3.0.0"
regex = "1.12.2"

